dns/generate_dns_snippet: removed unused type ignore
CI currently produces the following error

dns/generate_dns_snippets.py:303: error: Unused "type: ignore" comment
Found 1 error in 1 file (checked 2 source files)
ERROR: InvocationError for command /home/jbond/git/netbox-extras/.tox/py39-mypy/bin/mypy dns
tools/ganeti-netbox-sync.py (exited with code 1)

Change-Id: Ibf3237c0ac7c512b6cb46cdb44fd2998c39af20e